name: "Deploy to Codigofacilito"
on: 
  push:
    branches: ["master"]

jobs:
  deploy-codigofacilito:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "Hacemos pull del codigofacilito"
      - run: echo "Correr migraciones"
      - run: echo "Gnerrar binario"
      - run: echo "Publicar versión"
